import "./globals.css";
import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";
// import { Geist, Geist_Mono } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="id"
      suppressHydrationWarning
      // className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* antialiased: biar pinggiran text alus di layar */}
      <body className="antialiased bg-background text-foreground">
        <div className="flex h-screen w-full overflow-hidden relative border-2 border-amber-500">
          {/* Sidebar */}
          <Sidebar />
          {/* End Sidebar */}
          {children}
        </div>
      </body>
    </html>
  );
}
